import Link from "next/link";
import { MercadoSidebar } from "@/components/mercado/MercadoSidebar";
import { MercadoOverview } from "@/components/mercado/MercadoOverview";
import { VolumeMensalSection } from "@/components/mercado/VolumeMensalSection";
import { TendenciaSection } from "@/components/mercado/TendenciaSection";
import { EficienciaSection } from "@/components/mercado/EficienciaSection";
import { CaptacaoRealSection } from "@/components/mercado/CaptacaoRealSection";
import { SegmentacaoSection } from "@/components/mercado/SegmentacaoSection";
import { PipelineSection } from "@/components/mercado/PipelineSection";
import { SecuritizacaoSection } from "@/components/mercado/SecuritizacaoSection";
import type {
  OverviewData,
  TendenciaData,
  EficienciaData,
  SegmentacaoData,
  PipelineData,
  VolumeMensalData,
  CaptacaoRealData,
  SecuritizacaoData,
} from "@/types/mercado";

// JSON files generated by export_json.py — imported statically at build time
import overviewRaw from "@/public/data/mercado_overview.json";
import volumeMensalRaw from "@/public/data/mercado_volume_mensal.json";
import tendenciaRaw from "@/public/data/mercado_tendencia.json";
import eficienciaRaw from "@/public/data/mercado_eficiencia.json";
import captacaoRaw from "@/public/data/mercado_captacao_real.json";
import segmentacaoRaw from "@/public/data/mercado_segmentacao.json";
import pipelineRaw from "@/public/data/mercado_pipeline.json";
import securitizacaoRaw from "@/public/data/mercado_securitizacao.json";

const overview = overviewRaw as OverviewData;
const volumeMensal = volumeMensalRaw as VolumeMensalData;
const tendencia = tendenciaRaw as TendenciaData;
const eficiencia = eficienciaRaw as EficienciaData;
const captacao = captacaoRaw as CaptacaoRealData;
const segmentacao = segmentacaoRaw as SegmentacaoData;
const pipeline = pipelineRaw as PipelineData;
const securitizacao = securitizacaoRaw as SecuritizacaoData;

export default function MercadoPage() {
  const today = new Date().toLocaleDateString("pt-BR", {
    day: "2-digit",
    month: "long",
    year: "numeric",
  });
  const dataBase = overview?.data_base ?? null;

  return (
    <div className="min-h-screen bg-[#f8f9fb]">
      <header className="sticky top-0 z-20 border-b border-gray-200 bg-white/90 backdrop-blur-sm">
        <div className="mx-auto flex max-w-screen-2xl items-center justify-between px-4 py-3 sm:px-6 lg:px-8">
          <div>
            <h1 className="text-lg font-bold text-[#0F3443]">
              Análise de Mercado
            </h1>
            <p className="text-xs text-gray-500">
              FIDC · FII · FIP — Visão consolidada
            </p>
          </div>
          <div className="flex items-center gap-4">
            <span className="text-xs text-gray-400">
              Atualizado: {today}
              {dataBase && (
                <span className="ml-2 font-medium text-gray-500">· Data base CVM: {dataBase}</span>
              )}
            </span>
            <Link
              href="/"
              className="rounded-lg border border-[#0F3443] px-3 py-1.5 text-xs font-medium text-[#0F3443] transition-colors hover:bg-[#0F3443] hover:text-white"
            >
              ← Ofertas CVM 160
            </Link>
          </div>
        </div>
      </header>

      <MercadoSidebar />
      <div className="lg:pl-48">
        <main className="mx-auto max-w-screen-2xl space-y-8 px-4 py-6 sm:px-6 lg:px-8">
          <div id="visao-geral"><MercadoOverview data={overview} /></div>
          <div id="volume-mensal"><VolumeMensalSection data={volumeMensal} dataBase={dataBase} /></div>
          <div id="historico-volume"><TendenciaSection data={tendencia} dataBase={dataBase} /></div>
          <div id="metricas-captacao"><EficienciaSection data={eficiencia} dataBase={dataBase} /></div>
          <div id="taxa-sucesso"><CaptacaoRealSection data={captacao} dataBase={dataBase} /></div>
          <div id="mercado-capitais"><SecuritizacaoSection data={securitizacao} /></div>
          <div id="segmentacao"><SegmentacaoSection data={segmentacao} dataBase={dataBase} /></div>
          <div id="sazonalidade"><PipelineSection data={pipeline} dataBase={dataBase} /></div>
        </main>
      </div>
    </div>
  );
}
