import Link from "next/link";
import { KPICards } from "@/components/KPICards";
import { FundTypeChart } from "@/components/FundTypeChart";
import { VolumeChart } from "@/components/VolumeChart";
import { ChartsSection } from "@/components/ChartsSection";
import { RankingsSection } from "@/components/RankingsSection";
import { OfertasTable } from "@/components/OfertasTable";
import type { SummaryData, Oferta } from "@/types/oferta";

// JSON files are generated by export_json.py and placed in public/data/
// During build they are imported statically — no server needed.
import summaryRaw from "@/public/data/summary.json";
import ofertasRaw from "@/public/data/ofertas.json";

const summary = summaryRaw as SummaryData;
const ofertas = ofertasRaw as Oferta[];

export default function Home() {
  const today = new Date().toLocaleDateString("pt-BR", {
    day: "2-digit",
    month: "long",
    year: "numeric",
  });

  return (
    <div className="min-h-screen bg-[#f8f9fb]">
      {/* Header */}
      <header className="sticky top-0 z-10 border-b border-gray-200 bg-white/90 backdrop-blur-sm">
        <div className="mx-auto flex max-w-screen-2xl items-center justify-between px-4 py-3 sm:px-6 lg:px-8">
          <div>
            <h1 className="text-lg font-bold text-[#1e3a5f]">Ofertas CVM 160</h1>
            <p className="text-xs text-gray-500">FIDC · FII · FIP</p>
          </div>
          <div className="flex items-center gap-4">
            <span className="text-xs text-gray-400">Atualizado: {today}</span>
            <Link
              href="/mercado/"
              className="rounded-lg border border-[#1e3a5f] px-3 py-1.5 text-xs text-[#1e3a5f] font-medium hover:bg-[#1e3a5f] hover:text-white transition-colors"
            >
              Análise de Mercado
            </Link>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-screen-2xl space-y-6 px-4 py-6 sm:px-6 lg:px-8">
        {/* KPIs */}
        <KPICards summary={summary} />

        {/* Gráficos de pizza e barras */}
        <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
          <FundTypeChart por_tipo={summary.por_tipo} />
          <VolumeChart por_mes={summary.por_mes} />
        </div>

        {/* Gráficos horizontais */}
        <ChartsSection
          porTipo={summary.por_tipo_60d.map((d) => ({ label: d.tipo_ativo, value: d.volume }))}
          porStatus={summary.por_status_12m.map((d) => ({ label: d.status_cvm, value: d.n }))}
        />

        {/* Rankings */}
        {summary.top_emissores.length > 0 && summary.top_coordenadores.length > 0 && (
          <RankingsSection
            top_emissores={summary.top_emissores}
            top_coordenadores={summary.top_coordenadores}
          />
        )}

        {/* Tabela de ofertas — filtragem/paginação no cliente */}
        <div>
          <h2 className="mb-3 text-base font-semibold text-[#1e3a5f]">Ofertas Públicas</h2>
          <OfertasTable data={ofertas} />
        </div>
      </main>
    </div>
  );
}
